# Generated by Django 2.0.2 on 2018-03-20 08:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('priority', models.IntegerField(choices=[(1, 'high'), (2, 'middle'), (3, 'low')])),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('due', models.IntegerField(choices=[(1, 'middle month'), (2, 'D-5'), (3, 'D-4'), (4, 'D-3'), (5, 'D-2'), (6, 'D-1'), (7, 'D1'), (8, 'D2'), (9, 'D3'), (10, 'D4'), (11, 'D5')])),
                ('frequency', models.IntegerField(choices=[(1, 'monthly'), (2, 'quarterly'), (3, 'yearly'), (4, 'ad hoc')])),
                ('status', models.IntegerField(choices=[(1, 'not started'), (2, 'in progress'), (3, 'completed'), (4, 'approved')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='trim_app.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_approver', to='trim_app.TeamMember'),
        ),
        migrations.AddField(
            model_name='task',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_backup', to='trim_app.TeamMember'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='trim_app.Team'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_person', to='trim_app.TeamMember'),
        ),
    ]
