# Generated by Django 2.0.2 on 2018-03-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trim_app', '0003_auto_20180320_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='backup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_backup', to='trim_app.TeamMember'),
        ),
    ]
