# Generated by Django 2.0.2 on 2018-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trim_app', '0004_auto_20180320_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
