# Generated by Django 2.0.2 on 2018-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trim_app', '0005_auto_20180320_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'not started'), (2, 'in progress'), (3, 'completed')]),
        ),
    ]
