# Generated by Django 2.0.2 on 2018-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trim_app', '0006_auto_20180323_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=3),
            preserve_default=False,
        ),
    ]
